version: '3.8'

services:
  db:
    image: ankane/pgvector:latest  # PostgreSQL with pgvector extension
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
